TAX_RATES_SETTING_LABEL = 'tax_rates'
DISCOUNTS_SETTING_LABEL = 'discounts'
KNOWN_STATE_CODES_SETTING_LABEL = 'known_state_codes'
APP_SETTINGS_LABEL = 'settings'

PRICE_GET_PARAM_LABEL = 'price'
QUANTITY_GET_PARAM_LABEL = 'quantity'
STATE_CODE_GET_PARAM_LABEL = 'state_code'

GET_PARAMS_ERROR_MESSAGE = 'GET_PARAMS_ERROR'
UNKNOWN_ERROR_MESSAGE = 'UNKNOWN_ERROR'
UNKNOWN_STATE_CODE_GET_PARAM_ERROR_MESSAGE = \
    'UNKNOWN_STATE_CODE_GET_PARAM_ERROR_MESSAGE'
